version: 2

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore npm cache
      keys:
        - npm-cache-{{ checksum "package.json" }}
        - npm-cache-

  persist_cache: &persist_cache
    save_cache:
      name: Save npm cache
      key: npm-cache-{{ checksum "package.json" }}
      paths:
        - ../.npm

jobs:
  lint:
    docker:
      - image: circleci/node:11.8.0
    environment:
      NODE_ENV: circleci
      CYPRESS_INSTALL_BINARY: 0

    steps:
      - checkout
      - <<: *restore_cache
      - run: npm ci
      - <<: *persist_cache

      - run: npm run lint
      - run: npm run prettier:check

  jest:
    docker:
      - image: circleci/node:11.8.0
    environment:
      NODE_ENV: circleci
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - checkout
      - <<: *restore_cache
      - run: npm ci
      - <<: *persist_cache

      - run: npm run test:jest

  build:
    docker:
      - image: circleci/node:11.8.0
    environment:
      NODE_ENV: circleci
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - checkout
      - <<: *restore_cache
      - run: npm ci
      - <<: *persist_cache

      - run: npm run build:clean
      - run: npm run build:updates
      - run: npm run build:server
      - run: npm run build:next

      - persist_to_workspace:
          root: .
          paths:
            - cypress
            - dist
            - scripts
            - src
            - test
            - .babelrc
            - cypress.json
            - package.json
            - package-lock.json

  e2e:
    docker:
      - image: circleci/node:11.8.0
      - image: circleci/postgres:9.6.8-alpine-postgis-ram
      - image: circleci/redis
      - image: memcached
    environment:
      NODE_ENV: circleci
    steps:
      - run: sudo apt -y update
      - run: sudo apt -y install postgresql-client

      # Cypress dependencies
      # See: https://github.com/cypress-io/cypress-docker-images/blob/master/base/ubuntu16/Dockerfile
      - run: sudo apt -y install libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb

      - attach_workspace:
          at: .

      - <<: *restore_cache
      - run: CYPRESS_INSTALL_BINARY=0 npm ci
      - <<: *persist_cache

      - restore_cache:
          keys:
            - cypress-cache-{{ checksum "package.json" }}
            - cypress-cache-

      - run: npx cypress install

      - save_cache:
          key: cypress-cache-{{ checksum "package.json" }}
          paths:
            # This is the cache for the cypress binary
            - ../.cache

      - run: ./scripts/setup_circleci.sh

      - run: npm run test:e2e

      - store_test_results:
          path: /tmp/circleci-test-results

workflows:
  version: 2
  lint-jest-build-e2e:
    jobs:
      - lint
      - jest
      - build
      - e2e:
          requires:
            - build
