version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:11.8.0
    environment:
      NODE_ENV: circleci
      CYPRESS_INSTALL_BINARY: 0

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - npm-cache-{{ checksum "package.json" }}
            # Find the most recently generated cache used from any branch
            - npm-cache-

      - run: npm ci

      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            # This is the global npm cache
            - ../.npm

      - run: npm run lint

  jest:
    docker:
      - image: circleci/node:11.8.0
    environment:
      NODE_ENV: circleci
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package.json" }}
            - npm-cache-

      - run: npm ci

      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            - ../.npm

      - run: npm run test:jest

  e2e:
    docker:
      - image: circleci/node:11.8.0
      - image: circleci/postgres:9.6.8-alpine-postgis-ram
      - image: circleci/redis
      - image: memcached
    environment:
      NODE_ENV: circleci
    steps:
      - checkout
      - setup_remote_docker

      - run: sudo apt -y update
      - run: sudo apt -y install postgresql-client

      # Cypress dependencies
      # See: https://github.com/cypress-io/cypress-docker-images/blob/master/base/ubuntu16/Dockerfile
      - run: sudo apt -y install libgtk2.0-0
      - run: sudo apt -y install libnotify-dev
      - run: sudo apt -y install libgconf-2-4 libnss3 libxss1
      - run: sudo apt -y install libasound2 xvfb

      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package.json" }}
            - npm-cache-

      - restore_cache:
          keys:
            - cypress-cache-{{ checksum "package.json" }}
            - cypress-cache-

      - run: npm ci

      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            # This is the global npm cache
            - ../.npm

      - save_cache:
          key: cypress-cache-{{ checksum "package.json" }}
          paths:
            # This is the cache for the cypress binary
            - ../.cache

      - run: npm run build:clean
      - run: npm run build:updates
      - run: npm run build:server
      - run: npm run build:next

      - run: ./scripts/setup_circleci.sh

      - run: npm run test:e2e

      - store_test_results:
          path: /tmp/circleci-test-results

workflows:
  version: 2
  lint-jest-build:
    jobs:
      - lint
      - jest
      - e2e
